[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[theme]
base = "dark"
primaryColor = "#2563EB"
backgroundColor = "#0F172A"
secondaryBackgroundColor = "#111827"
textColor = "#F9FAFB"
